liip_imagine:
    # As mentioned above, gd, imagick or gmagick are possible
    driver: "imagick"
    cache:                default
    data_loader:          owl_carousel
    default_image:        null
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "images/cache"
    loaders:
        owl_carousel:
            filesystem:
                data_root: "%kernel.project_dir%/public/"

    filter_sets:
        cache: ~

        # the name of the "filter set"
        owl_carousel:

            # adjust the image quality to 75%
            quality: 75

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [120, 90], mode: outbound }
