vich_uploader:

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    db_driver: orm
    templating: true        # set to false to disable templating integration
    twig:       true        # set to false to disable twig integration (requires templating)
    form:       true        # set to false to disable form integration
    storage:    file_system # or gaufrette or flysystem
    metadata:
        auto_detection: true
        cache:          file
    mappings:
        logo:
            uri_prefix: /uploads/client/profil/logo
            upload_destination: '%kernel.project_dir%/public/uploads/client/profil/logo'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true
        identity:
            uri_prefix: /uploads/client/profil/identity
            upload_destination: '%kernel.project_dir%/public/uploads/client/profil/identity'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true
        pieceJointe:
            uri_prefix: /uploads/client/profil/pieceJointe
            upload_destination: '%kernel.project_dir%/public/uploads/client/profil/pieceJointe'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true
        report:
            uri_prefix: /uploads/client/support/report
            upload_destination: '%kernel.project_dir%/public/uploads/client/support/report'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false
