<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200517145120 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE cli_utilisateur ADD plan VARCHAR(255) NOT NULL, ADD plan_started_at DATETIME DEFAULT NULL, CHANGE profil profil INT DEFAULT NULL, CHANGE client client INT DEFAULT NULL, CHANGE username username VARCHAR(90) DEFAULT NULL, CHANGE password_requested_at password_requested_at DATETIME DEFAULT NULL, CHANGE token token VARCHAR(255) DEFAULT NULL, CHANGE dateInscription dateInscription DATETIME DEFAULT NULL, CHANGE lastLogin lastLogin DATETIME DEFAULT NULL, CHANGE cgu cgu TINYINT(1) DEFAULT NULL, CHANGE ip ip VARCHAR(255) DEFAULT NULL, CHANGE userAgent userAgent VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_support_pj CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_size image_size INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_support_report CHANGE utilisateur_id utilisateur_id INT DEFAULT NULL, CHANGE pj pj INT DEFAULT NULL, CHANGE date date DATETIME DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE sujet sujet VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_skills_criteria CHANGE competence competence INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE acquired acquired INT DEFAULT NULL, CHANGE toAcquire toAcquire INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_skills CHANGE utilisateur utilisateur INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_immigration CHANGE publish publish DATE DEFAULT NULL, CHANGE exp exp DATE DEFAULT NULL, CHANGE statut statut VARCHAR(255) DEFAULT NULL, CHANGE publishedby publishedby VARCHAR(255) DEFAULT NULL, CHANGE eval eval DATE DEFAULT NULL, CHANGE comment comment VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_immigration_piece_jointe CHANGE commentaire commentaire VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil CHANGE informations_entreprise informations_entreprise INT DEFAULT NULL, CHANGE informations_personnelles informations_personnelles INT DEFAULT NULL, CHANGE coordonnees coordonnees INT DEFAULT NULL, CHANGE emploi emploi INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_contact CHANGE landline landline VARCHAR(15) DEFAULT NULL, CHANGE phone phone VARCHAR(15) DEFAULT NULL, CHANGE professionalphone professionalphone VARCHAR(15) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_contact_piece_jointe CHANGE commentaire commentaire VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_certification_exp CHANGE start start DATE DEFAULT NULL, CHANGE end end DATE DEFAULT NULL, CHANGE comment comment VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_certification_langues CHANGE skill skill VARCHAR(30) DEFAULT NULL, CHANGE comment comment VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_certification_permis CHANGE number number VARCHAR(30) DEFAULT NULL, CHANGE start start DATE DEFAULT NULL, CHANGE end end DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_certification_skill CHANGE years_exp years_exp VARCHAR(30) DEFAULT NULL, CHANGE comment comment VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_cert_piece_jointe CHANGE commentaire commentaire VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_certification_etudes CHANGE institute institute VARCHAR(30) DEFAULT NULL, CHANGE speciality speciality VARCHAR(30) DEFAULT NULL, CHANGE result result VARCHAR(1000) DEFAULT NULL, CHANGE start start DATE DEFAULT NULL, CHANGE end end DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_info_identity CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_size image_size INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_informations_personnelles CHANGE identity_id identity_id INT DEFAULT NULL, CHANGE civilite civilite VARCHAR(3) DEFAULT NULL, CHANGE identifiant identifiant VARCHAR(33) DEFAULT NULL, CHANGE firstname firstname VARCHAR(99) DEFAULT NULL, CHANGE middlename middlename VARCHAR(99) DEFAULT NULL, CHANGE lastname lastname VARCHAR(99) DEFAULT NULL, CHANGE nickname nickname VARCHAR(99) DEFAULT NULL, CHANGE familysituation familysituation VARCHAR(33) DEFAULT NULL, CHANGE dob dob DATE DEFAULT NULL, CHANGE birthplace birthplace VARCHAR(255) DEFAULT NULL, CHANGE ssn ssn VARCHAR(33) DEFAULT NULL, CHANGE idupdate idupdate INT DEFAULT NULL, CHANGE nameupdate nameupdate VARCHAR(255) DEFAULT NULL, CHANGE dateupdate dateupdate DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_info_piece_jointe CHANGE commentaire commentaire VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_personnes CHANGE dob dob DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_perso_piece_jointe CHANGE commentaire commentaire VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_emploi CHANGE job job VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE statut statut VARCHAR(255) DEFAULT NULL, CHANGE structure structure VARCHAR(255) DEFAULT NULL, CHANGE started_at started_at DATETIME DEFAULT NULL, CHANGE start start DATETIME DEFAULT NULL, CHANGE end end DATETIME DEFAULT NULL, CHANGE info info VARCHAR(255) DEFAULT NULL, CHANGE idupdate idupdate INT DEFAULT NULL, CHANGE nameupdate nameupdate VARCHAR(255) DEFAULT NULL, CHANGE dateupdate dateupdate DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_emploi_piece_jointe CHANGE commentaire commentaire VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_logo CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_size image_size INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_informations_entreprise CHANGE logo logo INT DEFAULT NULL, CHANGE nom_entreprise nom_entreprise VARCHAR(255) NOT NULL, CHANGE idupdate idupdate INT DEFAULT NULL, CHANGE nameupdate nameupdate VARCHAR(255) DEFAULT NULL, CHANGE dateupdate dateupdate DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_info_entreprise_piece_jointe CHANGE commentaire commentaire VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_salaire_piece_jointe CHANGE commentaire commentaire VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_coordonnees CHANGE address address VARCHAR(255) DEFAULT NULL, CHANGE addresscontinued addresscontinued VARCHAR(255) DEFAULT NULL, CHANGE city city VARCHAR(55) DEFAULT NULL, CHANGE postalcode postalcode INT DEFAULT NULL, CHANGE country country VARCHAR(255) DEFAULT NULL, CHANGE state state VARCHAR(255) DEFAULT NULL, CHANGE landline landline VARCHAR(255) DEFAULT NULL, CHANGE phone phone VARCHAR(255) DEFAULT NULL, CHANGE professionalphone professionalphone VARCHAR(255) DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE idupdate idupdate INT DEFAULT NULL, CHANGE nameupdate nameupdate VARCHAR(255) DEFAULT NULL, CHANGE dateupdate dateupdate DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_coordonnees_piece_jointe CHANGE commentaire commentaire VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_reporter_piece_jointe CHANGE commentaire commentaire VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_absence CHANGE utilisateur utilisateur INT DEFAULT NULL, CHANGE note note VARCHAR(255) DEFAULT NULL, CHANGE is_active is_active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_planning_event CHANGE title title VARCHAR(255) DEFAULT NULL, CHANGE color color VARCHAR(255) DEFAULT NULL, CHANGE start start DATETIME DEFAULT NULL, CHANGE end end DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_planning_tache CHANGE client client INT DEFAULT NULL, CHANGE color color VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_notification CHANGE utilisateur utilisateur INT DEFAULT NULL, CHANGE message message VARCHAR(255) DEFAULT NULL, CHANGE slide slide INT DEFAULT NULL, CHANGE date date DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE adm_alerte CHANGE utilisateur utilisateur INT DEFAULT NULL, CHANGE niveau niveau INT DEFAULT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE url url VARCHAR(255) DEFAULT NULL, CHANGE ip ip VARCHAR(255) DEFAULT NULL, CHANGE userAgent userAgent VARCHAR(255) DEFAULT NULL, CHANGE date date DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE adm_utilisateur CHANGE password_requested_at password_requested_at DATETIME DEFAULT NULL, CHANGE token token VARCHAR(255) DEFAULT NULL, CHANGE dateInscription dateInscription DATETIME DEFAULT NULL, CHANGE lastLogin lastLogin DATETIME DEFAULT NULL, CHANGE ip ip VARCHAR(255) DEFAULT NULL, CHANGE userAgent userAgent VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE adm_alerte CHANGE utilisateur utilisateur INT DEFAULT NULL, CHANGE niveau niveau INT DEFAULT NULL, CHANGE type type VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE url url VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ip ip VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE userAgent userAgent VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE date date DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE adm_utilisateur CHANGE password_requested_at password_requested_at DATETIME DEFAULT \'NULL\', CHANGE token token VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE dateInscription dateInscription DATETIME DEFAULT \'NULL\', CHANGE lastLogin lastLogin DATETIME DEFAULT \'NULL\', CHANGE ip ip VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE userAgent userAgent VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_absence CHANGE utilisateur utilisateur INT DEFAULT NULL, CHANGE note note VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE is_active is_active TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cli_logo CHANGE image_name image_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE image_size image_size INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cli_notification CHANGE utilisateur utilisateur INT DEFAULT NULL, CHANGE message message VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE slide slide INT DEFAULT NULL, CHANGE date date DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cli_planning_event CHANGE title title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE color color VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE start start DATETIME DEFAULT \'NULL\', CHANGE end end DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cli_planning_tache CHANGE client client INT DEFAULT NULL, CHANGE color color VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_profil CHANGE informations_entreprise informations_entreprise INT DEFAULT NULL, CHANGE informations_personnelles informations_personnelles INT DEFAULT NULL, CHANGE coordonnees coordonnees INT DEFAULT NULL, CHANGE emploi emploi INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_profil_cert_piece_jointe CHANGE commentaire commentaire VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_profil_certification_etudes CHANGE institute institute VARCHAR(30) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE speciality speciality VARCHAR(30) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE result result VARCHAR(1000) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE start start DATE DEFAULT \'NULL\', CHANGE end end DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cli_profil_certification_exp CHANGE start start DATE DEFAULT \'NULL\', CHANGE end end DATE DEFAULT \'NULL\', CHANGE comment comment VARCHAR(1000) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_profil_certification_langues CHANGE skill skill VARCHAR(30) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE comment comment VARCHAR(1000) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_profil_certification_permis CHANGE number number VARCHAR(30) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE start start DATE DEFAULT \'NULL\', CHANGE end end DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cli_profil_certification_skill CHANGE years_exp years_exp VARCHAR(30) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE comment comment VARCHAR(1000) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_profil_contact CHANGE landline landline VARCHAR(15) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE phone phone VARCHAR(15) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE professionalphone professionalphone VARCHAR(15) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_profil_contact_piece_jointe CHANGE commentaire commentaire VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_profil_coordonnees CHANGE address address VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE addresscontinued addresscontinued VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE city city VARCHAR(55) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE postalcode postalcode INT DEFAULT NULL, CHANGE country country VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE state state VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE landline landline VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE phone phone VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE professionalphone professionalphone VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE email email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE idupdate idupdate INT DEFAULT NULL, CHANGE nameupdate nameupdate VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE dateupdate dateupdate DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cli_profil_coordonnees_piece_jointe CHANGE commentaire commentaire VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_profil_emploi CHANGE job job VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE statut statut VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE structure structure VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE started_at started_at DATETIME DEFAULT \'NULL\', CHANGE start start DATETIME DEFAULT \'NULL\', CHANGE end end DATETIME DEFAULT \'NULL\', CHANGE info info VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE idupdate idupdate INT DEFAULT NULL, CHANGE nameupdate nameupdate VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE dateupdate dateupdate DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cli_profil_emploi_piece_jointe CHANGE commentaire commentaire VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_profil_immigration CHANGE publish publish DATE DEFAULT \'NULL\', CHANGE exp exp DATE DEFAULT \'NULL\', CHANGE statut statut VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE publishedby publishedby VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE eval eval DATE DEFAULT \'NULL\', CHANGE comment comment VARCHAR(1000) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_profil_immigration_piece_jointe CHANGE commentaire commentaire VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_profil_info_entreprise_piece_jointe CHANGE commentaire commentaire VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_profil_info_identity CHANGE image_name image_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE image_size image_size INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cli_profil_info_piece_jointe CHANGE commentaire commentaire VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_profil_informations_entreprise CHANGE logo logo INT DEFAULT NULL, CHANGE nom_entreprise nom_entreprise VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE idupdate idupdate INT DEFAULT NULL, CHANGE nameupdate nameupdate VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE dateupdate dateupdate DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cli_profil_informations_personnelles CHANGE identity_id identity_id INT DEFAULT NULL, CHANGE civilite civilite VARCHAR(3) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE identifiant identifiant VARCHAR(33) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE firstname firstname VARCHAR(99) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE middlename middlename VARCHAR(99) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE lastname lastname VARCHAR(99) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE nickname nickname VARCHAR(99) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE familysituation familysituation VARCHAR(33) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE dob dob DATE DEFAULT \'NULL\', CHANGE birthplace birthplace VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ssn ssn VARCHAR(33) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE idupdate idupdate INT DEFAULT NULL, CHANGE nameupdate nameupdate VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE dateupdate dateupdate DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cli_profil_perso_piece_jointe CHANGE commentaire commentaire VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_profil_personnes CHANGE dob dob DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cli_profil_reporter_piece_jointe CHANGE commentaire commentaire VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_profil_salaire_piece_jointe CHANGE commentaire commentaire VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_skills CHANGE utilisateur utilisateur INT DEFAULT NULL, CHANGE name name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_skills_criteria CHANGE competence competence INT DEFAULT NULL, CHANGE name name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE acquired acquired INT DEFAULT NULL, CHANGE toAcquire toAcquire INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cli_support_pj CHANGE image_name image_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE image_size image_size INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cli_support_report CHANGE utilisateur_id utilisateur_id INT DEFAULT NULL, CHANGE pj pj INT DEFAULT NULL, CHANGE date date DATETIME DEFAULT \'NULL\', CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE sujet sujet VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cli_utilisateur DROP plan, DROP plan_started_at, CHANGE profil profil INT DEFAULT NULL, CHANGE client client INT DEFAULT NULL, CHANGE username username VARCHAR(90) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE password_requested_at password_requested_at DATETIME DEFAULT \'NULL\', CHANGE token token VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE dateInscription dateInscription DATETIME DEFAULT \'NULL\', CHANGE lastLogin lastLogin DATETIME DEFAULT \'NULL\', CHANGE cgu cgu TINYINT(1) DEFAULT \'NULL\', CHANGE ip ip VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE userAgent userAgent VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
    }
}
